# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-13 13:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='城市')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='机构名称')),
                ('desc', models.TextField(max_length=100, verbose_name='机构描述')),
                ('category', models.CharField(choices=[('pxjg', '培训机构'), ('gr', '个人'), ('gxjg', '高校机构')], default='pxjg', max_length=4, verbose_name='机构类别')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('students', models.IntegerField(default=0, verbose_name='学习人数')),
                ('course_nums', models.IntegerField(default=0, verbose_name='课程数')),
                ('address', models.CharField(max_length=150, verbose_name='机构地址')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='封面')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '课程机构',
                'verbose_name_plural': '课程机构',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='教师ID')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='教师名')),
                ('image_url', models.CharField(default='N', max_length=200, verbose_name='头像')),
                ('work_position', models.CharField(max_length=50, verbose_name='公司职位')),
                ('teacher_desc', models.TextField(default='N', verbose_name='教师介绍')),
                ('exp', models.IntegerField(default=0, verbose_name='经验值')),
                ('following', models.IntegerField(default=0, verbose_name='关注人数')),
                ('fans', models.IntegerField(default=0, verbose_name='粉丝数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
    ]
