# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-13 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_name',
            field=models.CharField(max_length=200, verbose_name='章节名'),
        ),
    ]
