# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-13 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180213_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.CharField(default='N', max_length=200, verbose_name='视频链接'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_name',
            field=models.CharField(max_length=200, verbose_name='视频名'),
        ),
    ]
