# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-13 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomments',
            name='comment_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='comment_user_img',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='点赞者头像'),
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='fav_nums',
            field=models.IntegerField(blank=True, null=True, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='comments',
            field=models.TextField(max_length=200, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='coursecomments',
            name='user',
            field=models.CharField(max_length=50, verbose_name='用户'),
        ),
    ]
